# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v                                   # Print out ruby version for debugging
  # Uncomment next line if your rails app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y ); fi
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then eval $(ssh-agent -s); fi
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then mkdir -p ~/.ssh; fi
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then chmod 700 ~/.ssh; fi
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts; fi
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then chmod 644 ~/.ssh/known_hosts; fi

build:
  script:
    - bundle exec jekyll build
    - tar -caf rustrush.site.tar.bz _site
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then scp rustrush.site.tar.bz 'travis@battus.michaelpankov.com:' ; fi
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then ssh -t travis@battus.michaelpankov.com "rm -rf _site_rustrush 
      && mkdir -p _site_rustrush 
      && tar -xaf rustrush.site.tar.bz -C _site_rustrush
      && sudo /data/www/deploy_rustrush.sh"; fi